Let the user define dep_dir
semarie/build-rust pull request #25
Opened 2024-03-25 08:21 UTC by nalysius

The variable `dep_dir` can be defined in ~/.build_rust.conf, so it's easier to build several versions one after the other.
The default behaviour doesn't change, but the if defined, the user could use a build of Rust 1.73 to build 1.74, and so on.
I did it up to 1.77.

2024-03-25 14:52 UTC, semarie requested changes

2024-03-25 14:52 UTC, semarie commented on build.sh
> +	    if [[ -z "${dep_dir:-}" ]]; then
could you just use `${dep_dir}` ? the variable is expected to be defined.

2024-03-25 14:52 UTC, semarie commented on build.sh
> +		   dep_dir="/usr/local"
tab vs spaces

2024-03-25 14:52 UTC, semarie commented on build.sh
> +dep_dir="${dep_dir:-}"
I am unsure that using `dep_dir` name for a public variable is ideal. but it is fine for now.

2024-03-26 08:32 UTC, nalysius commented on build.sh
> +		   dep_dir="/usr/local"
Done.

2024-03-26 08:33 UTC, nalysius commented on build.sh
> +dep_dir="${dep_dir:-}"
I agree. I renamed it to `rust_base_dir`, but feel free to rename it if you prefer.

2024-03-26 08:50 UTC, merged

2024-03-26 08:50 UTC, semarie commented
thanks